### ISSUE TITLE
about the dataset used

### ISSUE THREAD

**Issue by LeeKeyu** [ftsvd/USAnotAI#1]
Hi Kim-Ann,

Thanks for your work. This is what I'am looking for! May I ask where the training data comes from? I haven't found any open-source abdominal US dataset yet.
Thank you!

Keyu

**Comment by ftsvd** [comment]
Hi Keyu,

I generated this dataset by myself using resources at my hospital. I had actually planned to create a larger dataset using volunteers at my hospital, but that plan is delayed due to Covid-19. I am not sure of the existence of other abdominal US datasets, so I can't help you there.

Kim-Ann

**Comment by LeeKeyu** [comment]
> 
> 
> Hi Keyu,
> 
> I generated this dataset by myself using resources at my hospital. I had actually planned to create a larger dataset using volunteers at my hospital, but that plan is delayed due to Covid-19. I am not sure of the existence of other abdominal US datasets, so I can't help you there.
> 
> Kim-Ann

OK I see. Thanks for your reply! 

Best,
Keyu
